service: sqs-course

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  environment:
    SQS_URL: !Ref SQS
    PAYMENTS_TABLE_NAME: !Ref PaymentsTable
  iam:
    role:
      statements:
        - Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Effect: Allow
          Resource: !GetAtt SQS.Arn
        - Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
          Effect: Allow
          Resource: !GetAtt PaymentsTable.Arn

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  placeOrder:
    handler: src/functions/place-order.handler
    events:
      - httpApi:
          path: /
          method: GET
  processPayment:
    handler: src/functions/process-payment.handler
    events:
      - sqs:
          arn: !GetAtt SQS.Arn
          batchSize: 10
          maximumBatchingWindow: 10

resources:
  Resources:
    SQS:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: orders_queue
        ReceiveMessageWaitTimeSeconds: 20
    PaymentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: payments
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
